class WT_G3x5_RegionNames {
    /**
     * Gets the name of the region associated with a specified ICAO region code.
     * @param {String} code - the 1-2 character ICAO region code.
     * @returns {String} the name of the region.
     */
    static getName(code) {
        let name = WT_G3x5_RegionNames.NAME_TABLE[code.toUpperCase()];
        return name === undefined ? "" : name;
    }
}
WT_G3x5_RegionNames.NAME_TABLE = {
    "AG": "SOLOMON ISL",
    "AN": "NAURU ISL",
    "AY": "PAPUA NEW GUINEA",
    "BG": "GREENLAND",
    "BI": "ICELAND",
    "BK": "KOSOVO",
    "CY": "CANADA",
    "DA": "ALGERIA",
    "DB": "BENIN",
    "DF": "BURKINA FASO",
    "DG": "GHANA",
    "DI": "IVORY COAST",
    "DN": "NIGERIA",
    "DR": "NIGER",
    "DT": "TUNISIA",
    "DX": "TOGO",
    "EB": "BELGIUM",
    "ED": "GERMANY",
    "EE": "ESTONIA",
    "EF": "FINLAND",
    "EG": "U KINGDOM",
    "EH": "NETHERLANDS",
    "EI": "IRELAND",
    "EK": "DENMARK",
    "EL": "LUXEMBOURG",
    "EN": "NORWAY",
    "EP": "POLAND",
    "ES": "SWEDEN",
    "ET": "GERMANY",
    "EV": "LATVIA",
    "EY": "LITHUANIA",
    "FA": "S AFRICA",
    "FB": "BOTSWANA",
    "FC": "REP CONGO",
    "FD": "ESWATINI",
    "FE": "CEN AFRICAN REP",
    "FG": "EQU GUINEA",
    "FH": "ASCENSION ISL",
    "FI": "MAURITIUS",
    "FJ": "BRIT INDIAN OC TERR",
    "FK": "CAMEROON",
    "FL": "ZAMBIA",
    "FM": "MADAGASCAR",
    "FN": "ANGOLA",
    "FO": "GABON",
    "FP": "SAO TOME",
    "FQ": "MOZAMBIQUE",
    "FS": "SEYCHELLES",
    "FT": "CHAD",
    "FV": "ZIMBABWE",
    "FW": "MALAWI",
    "FX": "LESOTHO",
    "FY": "NAMIBIA",
    "FZ": "DEM REP CONGO",
    "GA": "MALI",
    "GB": "GAMBIA",
    "GC": "CANARY ISL",
    "GE": "MELILLA",
    "GF": "SIERRA LEONE",
    "GG": "GUINEA BISSAU",
    "GL": "LIBERIA",
    "GM": "MOROCCO",
    "GO": "SENEGAL",
    "GQ": "MAURITANIA",
    "GS": "W SAHARA",
    "GU": "GUINEA",
    "GV": "CAPE VERDE",
    "HA": "ETHIOPIA",
    "HB": "BURUNDI",
    "HD": "DJIBOUTI",
    "HE": "EGYPT",
    "HH": "ERITREA",
    "HK": "KENYRA",
    "HL": "LIBYA",
    "HR": "RWANDA",
    "HS": "SUDAN",
    "HT": "TANZANIA",
    "HU": "UGANDA",
    "K1": "NW USA",
    "K2": "SW USA",
    "K3": "N CEN USA",
    "K4": "S CEN USA",
    "K5": "CEN USA",
    "K6": "NE USA",
    "K7": "SE USA",
    "LA": "ALBANIA",
    "LB": "BULGARIA",
    "LC": "CYPRUS",
    "LD": "CROATIA",
    "LE": "SPAIN",
    "LF": "FRANCE",
    "LG": "GREECE",
    "LH": "HUNGARY",
    "LI": "ITALY",
    "LJ": "SLOVENIA",
    "LK": "CZECH REP",
    "LL": "ISRAEL",
    "LM": "MALTA",
    "LO": "AUSTRIA",
    "LP": "PORTUGAL",
    "LQ": "BOSNIA AND HERZEGOVINIA",
    "LR": "ROMANIA",
    "LS": "SWITZERLAND",
    "LT": "TURKEY",
    "LU": "MOLDOVA",
    "LV": "PALESTINE",
    "LW": "MACEDONIA",
    "LX": "GIBRALTAR",
    "LY": "SERBIA AND MONTENEGRO",
    "LZ": "SLOVAKIA",
    "MB": "TURKS AND CAICOS ISL",
    "MD": "DOMINICAN REP",
    "MG": "GUATEMALA",
    "MH": "HONDURAS",
    "MK": "JAMAICA",
    "MM": "MEXICO",
    "MN": "NICARAGUA",
    "MP": "PANAMA",
    "MR": "COSTA RICA",
    "MS": "EL SALVADOR",
    "MT": "HAITI",
    "MU": "CUBA",
    "MW": "CAYMAN ISL",
    "MY": "BAHAMAS",
    "MZ": "BELIZE",
    "NC": "COOK ISL",
    "NF": "FIJI",
    "NG": "KIRIBATI ISL",
    "NI": "NIUE ISL",
    "NL": "WALLIS ISL",
    "NS": "AMERICAN SAMOA",
    "NT": "FRENCH POLYNESIA",
    "NV": "VANUATU",
    "NW": "NEW CALEDONIA",
    "NZ": "NEW ZEALAND",
    "OA": "AFGHANISTAN",
    "OB": "BAHRAIN",
    "OE": "SAUDI ARABIA",
    "OI": "IRAN",
    "OJ": "JORDAN",
    "OK": "KUWAIT",
    "OL": "LEBANON",
    "OM": "UAE",
    "OO": "OMAN",
    "OP": "PAKISTAN",
    "OR": "IRAQ",
    "OS": "SYRIA",
    "OT": "QATAR",
    "OY": "YEMEN",
    "PA": "ALASKA",
    "PG": "GUAM",
    "PH": "HAWAII",
    "PJ": "JOHNSTON ATOLL",
    "PK": "MARSHALL ISL",
    "PL": "KIRIBATI",
    "PM": "MIDWAY ISL",
    "PO": "ALASKA",
    "PP": "ALASKA",
    "PT": "MICRONESIA",
    "PW": "WAKE ISL",
    "RC": "TAIWAN",
    "RJ": "JAPAN",
    "RK": "S KOREA",
    "RO": "OKINAWA",
    "RP": "PHILIPPINES",
    "SA": "ARGENTINA",
    "SB": "BRAZIL",
    "SC": "CHILE",
    "SD": "BRAZIL",
    "SE": "EQUADOR",
    "SG": "PARAGUAY",
    "SI": "BRAZIL",
    "SJ": "BRAZIL",
    "SK": "COLOMBIA",
    "SL": "BOLIVIA",
    "SM": "SURINAM",
    "SO": "FRENCH GUYANA",
    "SP": "PERU",
    "SS": "BRAZIL",
    "SU": "URUGUAY",
    "SV": "VENEZUELA",
    "SW": "BRAZIL",
    "SY": "GUYANA",
    "TA": "ANTIGUA AND BARBUDA",
    "TB": "BARBADOS",
    "TD": "DOMINICA",
    "TF": "FRENCH ANTILLES",
    "TG": "GRENADA",
    "TI": "US VIRGIN ISL",
    "TJ": "PUERTO RICO",
    "TK": "ST KITTS",
    "TL": "ST LUCIA",
    "TN": "ARUBA",
    "TQ": "ANGUILLA",
    "TT": "MONSERRAT",
    "TU": "TRINIDAD AND TOBAGO",
    "TV": "UK VIRGIN ISL",
    "TX": "BERMUDA",
    "UA": "KAZAKHSTAN",
    "UB": "AZERBAIJAN",
    "UC": "KYRGYZSTAN",
    "UD": "ARMENIA",
    "UE": "E RUSSIA",
    "UG": "GEORGIA",
    "UH": "SE RUSSIA",
    "UI": "S CEN RUSSIA",
    "UK": "UKRAINE",
    "UL": "NW RUSSIA",
    "UM": "BELARUS",
    "UN": "S CEN RUSSIA",
    "UO": "N CEN RUSSIA",
    "UR": "SW RUSSIA",
    "US": "CEN RUSSIA",
    "UT": "TAJIKISTAN",
    "UU": "NW RUSSIA",
    "UW": "W RUSSIA",
    "VA": "W INDIA",
    "VC": "SRI LANKA",
    "VD": "CAMBODIA",
    "VE": "E INDIA",
    "VG": "BANGLADESH",
    "VH": "HONG KONG",
    "VI": "N INDIA",
    "VL": "LAOS",
    "VM": "MACAU",
    "VN": "NEPAL",
    "VO": "S INDIA",
    "VR": "MALDIVES",
    "VT": "THAILAND",
    "VV": "VIETNAM",
    "VY": "MYANMAR",
    "WA": "E INDONESIA",
    "WB": "BRUNEI",
    "WI": "W INDONESIA",
    "WM": "MALAYSIA",
    "WR": "CEN INDONESIA",
    "WS": "SINGAPORE",
    "YB": "AUSTRALIA",
    "YM": "AUSTRALIA",
    "ZB": "E CHINA",
    "ZG": "SE CHINA",
    "ZH": "E CHINA",
    "ZK": "N KOREA",
    "ZL": "CEN CHINA",
    "ZM": "MONGOLIA",
    "ZP": "S CEN CHINA",
    "ZS": "SE CHINA",
    "ZU": "SW CHINA",
    "ZW": "NW CHINA",
    "ZY": "NE CHINA",
};