name: CI - CJ4 Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Package
        run: powershell.exe -noexit .\build.ps1 -Project workingtitle-project-cj4.xml
      # - name: Upload Package
      #   uses: actions/upload-artifact@v2.1.4
      #   with:
      #     name: workingtitle-cj4
      #     path: |
      #       build/workingtitle-aircraft-cj4
      #       build/workingtitle-vcockpits-instruments-cj4
      #       build/workingtitle-vcockpits-instruments-airliners
      #     if-no-files-found: error
